services:
  db:
    image: mariadb:11.4
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo' 
    ports:
    - "3306:3306"
    tty: true
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
volumes:
  db_data: